platform :osx, '10.7'

pod 'MASShortcut'
pod 'DBPrefsWindowController'
pod 'SPMediaKeyTap'
pod 'INAppStoreWindow', :git => 'git://github.com/sonoramac/INAppStoreWindow.git'
pod 'AFNetworking'
pod 'INKeychainAccess'
pod 'HIDRemoteSDK'
pod 'OEGridView'